var gfc_bo=osapi,gfc_co="ceil";gfc_1[gfc_].Hi=gfc_Bd(20,function(a,b,c){return a?c<b?[]:a[gfc_Gc](gfc_d.min(b,a[gfc_B]),gfc_d.min(c,a[gfc_B])):[]});gfc_1[gfc_].share=gfc_Bd(18,function(){gfc_xn();return!1});gfc_1[gfc_].Cf=gfc_Bd(16,function(){return this.Hb.pop()});gfc_1[gfc_].hj=gfc_Bd(15,function(){var a=this.yd;a.valid?(this.d=this.Ng(this.yd),this.ii(a[gfc_hd])):(this.yd=null,this.render(a.actions,a[gfc_hd],a.params));this.Kg()});
gfc_oa(gfc_Gf[gfc_],gfc_Bd(3,function(){this.x=gfc_d[gfc_co](this.x);this.y=gfc_d[gfc_co](this.y);return this}));gfc_oa(gfc_If[gfc_],gfc_Bd(2,function(){gfc_ma(this,gfc_d[gfc_co](this[gfc_i]));gfc_Ia(this,gfc_d[gfc_co](this[gfc_u]));return this}));gfc_oa(gfc_yh[gfc_],gfc_Bd(1,function(){this.top=gfc_d[gfc_co](this.top);gfc_Ja(this,gfc_d[gfc_co](this[gfc_wc]));gfc_Ea(this,gfc_d[gfc_co](this[gfc_hc]));gfc_Qa(this,gfc_d[gfc_co](this[gfc_z]));return this}));
gfc_oa(gfc_zh[gfc_],gfc_Bd(0,function(){gfc_Qa(this,gfc_d[gfc_co](this[gfc_z]));this.top=gfc_d[gfc_co](this.top);gfc_ma(this,gfc_d[gfc_co](this[gfc_i]));gfc_Ia(this,gfc_d[gfc_co](this[gfc_u]));return this}));
var gfc_do=function(a){return a=gfc_b[gfc_md]+"/friendconnect/favicon?url="+escape(a)},gfc_7=function(a,b,c){this.Ha();this.Vr();var d=new gfc_R;d.set("members",{action:this.hv,callback:this.du});d.set("member-page",{action:this.gv,callback:this.cu});d.set("blocked-member-page",{action:this.av,callback:this.Zt});d.set("profile-friends-page",{action:this.mv,callback:this.hu});d.set("sitesData",{action:this.uv,callback:this.lu});d.set("viewerFriends",{action:this.zv,callback:this.nu});d.set("profileData",
{action:this.lv,callback:this.gu});d.set("blockUser",{action:this.$u,callback:this.Yt});d.set("unblockUser",{action:this.xv,callback:this.mu});d.set("profileFriends",{action:this.nv,callback:this.iu});d.set("activityData",{action:this.Nf,callback:this.hd});d.set("sendFriendRequest",{action:this.tv,callback:this.ku});d.set("sendFriendRequestResponse",{action:this.dv,callback:this.Am});d.set("deleteActivity",{action:this.Of,callback:this.hd});d.set("requestAndProcessViewerNumWaitingMessages",{action:this.Av,
callback:this.pu});d.set("requestPromo",{action:this.ov,callback:this.ju});this.lb=null;this.jy=new gfc_Fn("fc-members-options-menu",gfc_L(this.zt,this),gfc_L(this.yt,this),gfc_L(this.At,this),0,gfc_b[gfc_md],this.f("ENDCAP_LINK_COLOR")||"0000cc",this.f("CONTENT_TEXT_COLOR")||"000000");this.Lw=!1;this.Ba=10;this.wf=15;this.Hn=10;var e=gfc_1h(gfc_Jh()),f=gfc_eo;this.Vb=3;this.sc=8;this.bn=null;this.ma=this.sc*this.Vb;this.slimTopCapHeight=19;this.tinyTopCapHeight=8;this.isMessagingEnabled=a;this.isPromosEnabled=
b;this.isSocialShareEnabled=c;this.numWaitingMessages=0;this.promoCode=-1;this.promoHtml=null;this.Pb=new gfc_Bn;this.bi()&&(a=(a=this.f(f.FACE_SIZE))?gfc_ga(a):32,a+=6,this.Vb=gfc_d[gfc_8a]((e[gfc_i]-10)/a),e=340,e=this.f(f.HEIGHT),(f=this.f(f.NUMBER_ROWS))?(this.sc=gfc_ga(f),e=this.sc*a,this.bn=e+27):e&&(e=gfc_ga(e)-96,this.sc=gfc_d.max(2,gfc_d[gfc_8a](e/a)),this.bn=this.sc*a+27),this.ma=this.sc*this.Vb);gfc_1[gfc_G](this,d)};gfc_7.inherits(gfc_1);
gfc_Ca(gfc_7[gfc_],function(){gfc_7.i[gfc_t][gfc_G](this);gfc_9m("start");var a=gfc_a[gfc_r][gfc_Rc](),b=gfc_ca();(a=b.profileId||a.profileId)?(b={},b[gfc_e[gfc_x][gfc_q].ID]=a,a=new gfc_e[gfc_x](b),this.render(["profileData","profileFriends","activityData"],"profile",{person:a})):(a=["members","viewerFriends"],this.isMessagingEnabled&&a[gfc_v]("requestAndProcessViewerNumWaitingMessages"),this.isPromosEnabled&&!this.Lb()&&a[gfc_v]("requestPromo"),this.render(a,"faces"))});gfc_7[gfc_].e={};
gfc_7[gfc_].Ha=function(){this.e.MSG_SITE_MEMBERS="Members";this.e.MSG_BE_THE_FIRST="Be the first!";this.e.MSG_NO_SITE_MEMBERS="There are no members yet.";this.e.MSG_ALL_SITE_MEMBERS="All Members";this.e.MSG_ALL_BLOCKED_MEMBERS="All Blocked Members";this.e.MSG_NO_BLOCKED_MEMBERS="You have not blocked any members";this.e.MSG_YOUR_FRIENDS="Your Friends";this.e.MSG_ALL_YOUR_FRIENDS="All Your Friends";this.e.MSG_JFJ="Join and connect with others!";this.e.MSG_MANAGE="Manage members";this.e.MSG_SETTINGS=
"Settings";this.e.MSG_OPTIONS="Options";this.e.MSG_MEMBERS_SHARE="Share this page";this.e.MSG_BACK="Back";this.e.MSG_BACK_TO_TOP="Home";this.e.MSG_VIEW_MY_PROFILE="View my profile";this.e.MSG_ABOUT_ME="About me";this.e.MSG_MORE="More \u00bb";this.e.MSG_SHOW_BLOCKED="Show blocked members \u00bb";this.e.MSG_SHOW_ALL="\u00ab Show all members";this.e.MSG_LINK_IN_NETWORKS="Link in your social networks";this.e.MSG_ACTIVITIES="Activities";this.e.MSG_ALL_ACTIVITIES="More activities";this.e.MSG_DELETE_THIS=
"Delete";this.e.MSG_SITES="Sites I've joined";this.e.MSG_ALL_SITES="More sites I've joined";this.e.MSG_LINKS="Links";this.e.MSG_ALL_LINKS="More links";this.e.MSG_NO_ACTIVITIES="No activities to show";this.e.MSG_ADD_AS_FRIEND="Add as friend";this.e.MSG_SEND_MESSAGE="Send a message";this.e.MSG_BLOCK_USER="Block this user";this.e.MSG_UNBLOCK_USER="Unblock this user";this.e.MSG_USER_IS_ADMIN="Administrator";this.e.MSG_JOIN="Join this site";this.e.MSG_OR="or";this.e.MSG_SIGN_IN="Sign in";this.e.MSG_SIGN_OUT=
"Sign out";this.e.MSG_PREVIOUS="\u00ab Previous";this.e.MSG_NEXT="Next \u00bb";this.e.MSG_NEWER="\u00ab Newer";this.e.MSG_OLDER="Older \u00bb";this.e.MSG_ACCEPT_ALL_FRIEND_REQUESTS="Accept all";this.e.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Friend Connect sites.";this.e.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Friend Connect sites.";this.e.MSG_HELP_BLOCKMEMBER="Blocking a visitor removes them from the members list and prevents them from interacting with other visitors on your site";
this.e.MSG_INVITATION="Invitation:";this.e.MSG_SEND="Send";this.e.MSG_BLOCK="Block";this.e.MSG_IGNORE="Ignore";this.e.MSG_CANCEL="Cancel";this.e.MSG_SITE_SETTINGS="Site settings";this.e.MSG_ABOUT_FC="About Friend Connect";this.e.MSG_ALREADY_MEMBER="Already a member?";this.e.MSG_EDIT_PROFILE="Edit profile"};gfc_7[gfc_].oa={};
gfc_7[gfc_].Vr=function(){this.oa.MSG_SITE_MEMBERS="Followers";this.oa.MSG_NO_SITE_MEMBERS="There are no followers yet.";this.oa.MSG_SHOW_BLOCKED="Show blocked followers \u00bb";this.oa.MSG_SHOW_ALL="\u00ab Show all followers";this.oa.MSG_ALL_SITE_MEMBERS="All Followers";this.oa.MSG_ALL_BLOCKED_MEMBERS="All Blocked Followers";this.oa.MSG_NO_BLOCKED_MEMBERS="You have not blocked any followers";this.oa.MSG_LIKE_THIS_SITE="Like this blog?";this.oa.MSG_JOIN="Follow";this.oa.MSG_BACK_TO_TOP="Members";
this.oa.MSG_JFJ="Follow and connect with your friends!";this.oa.MSG_HELP_FRIENDREQUEST="You and your friends will see each other across all Following blogs and Friend Connect sites.";this.oa.MSG_HELP_FRIENDINVITE="Once you are friends, you will see each other across all Following blogs and Friend Connect sites."};
gfc_7[gfc_].K=function(a,b){var c=!0;if(b[gfc_o]&&b[gfc_o].person){var d={},e=b[gfc_o].person[gfc_3b]()+" is your friend";d.MSG_IS_FRIEND=e;e="You have invited "+(b[gfc_o].person[gfc_3b]()+" to be your friend");d.MSG_IS_INVITED=e;e=b[gfc_o].person[gfc_3b]()+"'s friends";d.MSG_PROFILE_FRIENDS=e;e="All "+(b[gfc_o].person[gfc_3b]()+"'s friends");d.MSG_ALL_PROFILE_FRIENDS=e;for(var f in d)this.h(a,f,d[f])}b.invitedBy&&b.invitedBy[gfc_3b]()&&(d=gfc_c[gfc_i]?gfc_c[gfc_i]:gfc_c[gfc_C][gfc_7c]+2,c=(d-135)/
8,d=(d-175)/8,c="View "+(gfc_Zm(b.invitedBy[gfc_3b](),c)+"'s profile"),d=gfc_Zm(b.invitedBy[gfc_3b](),d)+" invited you to this site",this.h(a,"MSG_VIEW_INVITER_PROFILE",c),this.h(a,"MSG_INVITED_YOU",d),this.Lw=!0,c=!1);d=this.numWaitingMessages+" messages waiting for you.";this.isMessagingEnabled&&0<this.numWaitingMessages&&(c=!1,this.h(a,"showWaitingMessages",!0),this.isMessagingEnabled&&(this.h(a,"MSG_NUM_WAITING_MESSAGES",d),this.h(a,"MSG_VIEW_AND_CONFIGURE_MESSAGING","View messages")));b.friendRequests&&
(0<b.friendRequests[gfc_Qb]()&&(c=!1),d=1==b.friendRequests[gfc_Qb]()?"New friend request \u00bb":"New friend requests ("+(b.friendRequests[gfc_Qb]()+") \u00bb"),this.h(a,"MSG_NEW_FRIEND_REQUESTS",d));if(this.lb){if(this.Dl(this.lb.themeId))for(f in this.oa)this.h(a,f,this.oa[f]);this.lb.signInPrompt&&this.h(a,"MSG_JOIN",this.lb.signInPrompt);this.lb.signOutPrompt&&this.h(a,"MSG_SIGN_OUT",this.lb.signOutPrompt)}this.h(a,"isViewerAdmin",b.isViewerAdmin);this.h(a,"isMessagingEnabled",this.isMessagingEnabled);
this.h(a,"acceptMessages",this.no);this.h(a,"isViewingSelf",b.viewer&&b[gfc_o]&&b[gfc_o].person&&b.viewer[gfc_E]()==b[gfc_o].person[gfc_E]());d=!1;if(b.owner&&(e=b.owner[gfc_I]("profileExtensions")))for(f in e)d=!0;this.h(a,"communityHasProfile",d);this.h(a,"promoHtml",c?this.promoHtml:null);this.h(a,"insertHtml",function(a,b){gfc_Ma(a,b)})};gfc_7[gfc_].Dl=function(a){return"blogger"==a};gfc_7[gfc_].dh=function(a,b,c,d){gfc_vn({id:a,text:b,version:this.Dl(this.lb.themeId)?1:null,style:c},d)};
gfc_7[gfc_].Q=function(a){function b(b,c){d.h(a,b,gfc_L(c,d))}this.h(a,"facesPerRow",this.Vb);for(var c in this.e)this.h(a,c,this.e[c]);var d=this;b("getThumbnail",this.xc);b("map",this.map);b("elide",gfc_Zm);b("safeSlice",this.Hi);b("showAllActivities",this.ww);b("transformActivity",this.hc);b("nextActivities",this.$s);b("previousActivities",this.Jt);b("showAllLinks",this.yw);b("transformLink",this.kx);b("nextLinks",this.et);b("previousLinks",this.Lt);b("showAllSites",this.Bw);b("transformSite",
this.lx);b("nextSites",this.lt);b("previousSites",this.Rt);b("showAllMembers",this.zw);b("showBlockedMembers",this.Dw);b("showUnblockedMembers",this.Uw);b("nextMembers",this.ft);b("nextBlockedMembers",this.at);b("previousMembers",this.Mt);b("previousBlockedMembers",this.Kt);b("showAllProfileFriends",this.Aw);b("nextProfileFriends",this.kt);b("previousProfileFriends",this.Qt);b("showAllViewerFriends",this.Cw);b("nextViewerFriends",this.mt);b("previousViewerFriends",this.St);b("isHome",this.Zh);b("goBack",
this.zh);b("goBackToHome",this.Nw);b("editSettings",this.Db);b("signout",this.signout);b("signin",this.signin);b("viewProfile",this.bo);b("blockUser",this.Kj);b("unblockUser",this.px);b("goToInviteFriend",this.Xq);b("sendMessageDialog",this.Uv);b("goToBlockMember",this.Wq);b("goToEditProfile",this.Db);b("goToViewerProfile",this.Yq);b("sendInvite",this.Tv);b("blockMember",this.Io);b("acceptFriendRequest",this.mo);b("ignoreFriendRequest",this.Ur);b("viewFriendRequests",this.yx);b("acceptAllFriendRequests",
this.lo);b("numPreviewFriends",this.Cq);b("numPreviewMembers",this.Dq);b("showInvitedBy",this.Jq)};
gfc_7[gfc_].Xk=function(a){a=gfc_d.max(1,a?this.sc-1:this.sc);var b=this.d[gfc_k].members?this.d[gfc_k].members[gfc_Qb]():0,c=this.d[gfc_k].friends?this.d[gfc_k].friends[gfc_Qb]():0,b=gfc_d[gfc_co](b/this.Vb),c=gfc_d[gfc_co](c/this.Vb);b>gfc_d[gfc_co](a/2)?c>gfc_d[gfc_8a](a/2)?(b=gfc_d[gfc_co](a/2),c=gfc_d[gfc_8a](a/2)):b=gfc_d.max(0,a-c):c>gfc_d[gfc_8a](a/2)&&(c=gfc_d.max(0,a-b));b*=this.Vb;c*=this.Vb;return a={numMembers:b,numFriends:c}};gfc_7[gfc_].Dq=function(a){return this.Xk(a).numMembers};
gfc_7[gfc_].Cq=function(a){return this.Xk(a).numFriends};gfc_7[gfc_].gv=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_D][gfc_Wc];d[e.FILTER]="PUBLICLY_VISIBLE";d[e.FIRST]=b[gfc_t];d[e.MAX]=b.pageSize?b.pageSize:this.ma;var f=[gfc_e[gfc_x][gfc_q].ID,gfc_e[gfc_x][gfc_q][gfc_3a],gfc_e[gfc_x][gfc_q][gfc_Db]];d[e[gfc_mc]]=f;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_9c];c.add(c[gfc_ac](gfc_Ce(),d),"ownerFriends");c[gfc_n](a)};
gfc_7[gfc_].cu=function(a){this.d[gfc_k].members=a.get("ownerFriends")[gfc_l]()};gfc_7[gfc_].av=function(a,b){var c=gfc_e[gfc_H](),d={},e=gfc_e[gfc_D][gfc_Wc];d[e.FIRST]=b[gfc_t];d[e.MAX]=b.pageSize?b.pageSize:this.ma;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_9c];e={};e[gfc_e[gfc_Kb][gfc_q][gfc_2b]]=gfc_e[gfc_Kb].PersonId.OWNER;e[gfc_e[gfc_Kb][gfc_q][gfc_Xb]]="BLOCKED";e[gfc_e[gfc_Kb][gfc_q][gfc_zc]]=1;e=gfc_e[gfc_vc](e);c.add(c[gfc_ac](e,d),"blockedMembers");c[gfc_n](a)};
gfc_7[gfc_].Zt=function(a){this.d[gfc_k].blockedMembers=a.get("blockedMembers")[gfc_l]()};gfc_7[gfc_].mv=function(a,b){var c=gfc_e[gfc_H](),d=b&&b.person&&b.person[gfc_E]()||this.v[gfc_o].person[gfc_E](),e={},f=gfc_e[gfc_D][gfc_Wc];e[f.FIRST]=b[gfc_t];e[f.MAX]=b.pageSize?b.pageSize:this.ma;d=this.im(d);e[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_9c];c.add(c[gfc_ac](d,e),"profileFriends");c[gfc_n](a)};
gfc_7[gfc_].im=function(a){var b={};b[gfc_e[gfc_Kb][gfc_q][gfc_2b]]=a;b[gfc_e[gfc_Kb][gfc_q][gfc_Xb]]="FRIENDS";b[gfc_e[gfc_Kb][gfc_q][gfc_zc]]=1;return gfc_e[gfc_vc](b)};gfc_7[gfc_].hu=function(a){this.d[gfc_k][gfc_o].friends=a.get("profileFriends")[gfc_l]()};gfc_7[gfc_].Cj=function(a){for(var b=gfc_e[gfc_k].getDataContext(),c=0;c<a[gfc_B];c++){var d=a[c],d=b.getDataSet(d);if(!d||d.code)return!1}return!0};
gfc_7[gfc_].hv=function(a){var b=this.ma,c=!b||24==b;c&&gfc_e[gfc_k]&&this.Cj(["ownerFriends","viewer","siteSettings","friendRequests"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(c=gfc_bo.newBatch(),b={userId:"@owner",groupId:"@friends",count:b,filterBy:"PUBLICLY_VISIBLE"},c.add("ownerFriends",gfc_bo.people.get(b)),c.add("viewer",gfc_bo.people.getViewer()),c.add("siteSettings",gfc_bo.extensions.get({command:"GetSiteSettings"})),c.add("friendRequests",gfc_bo.extensions.get({command:"GetFriendRequests",
params:'{"idSpec" : "VIEWER"}'})),(b=gfc_ca().psinvite)&&c.add("invitedBy",gfc_bo.extensions.get({command:"DecodeInvitation",params:{token:b}})),c.execute(a))};gfc_7[gfc_].du=function(a,b){this.d[gfc_k].members=gfc_ue(a.ownerFriends,gfc_pe);this.d[gfc_k].viewer=gfc_pe(a.viewer);this.Am(a,b,!0);this.lb=a[gfc_Xc];var c=gfc_ca();!c.psinvite||null!=this.d[gfc_k].viewer&&""!=this.d[gfc_k].viewer||(a.invitedBy&&(a.invitedBy.nickname=a.invitedBy.displayName),this.d[gfc_k].invitedBy=new gfc_e[gfc_x](a.invitedBy))};
gfc_7[gfc_].zv=function(a,b){b=b||{};var c=b.pageSize||this.maxFacesPerPage,d=!b[gfc_t]||0==b[gfc_t],e=!c||20==c;d&&e&&gfc_e[gfc_k]&&this.Cj(["friends","isViewerAdmin"])?a(gfc_e[gfc_k].getDataContext()[gfc_l]()):(d=gfc_bo.newBatch(),c={userId:"@viewer",groupId:"@friends",count:c},b[gfc_t]&&(c.startIndex=b[gfc_t]),d.add("friends",gfc_bo.people.get(c)),d.add("isViewerAdmin",gfc_bo.people.get({userId:"@viewer",groupId:"ADMINS"})),d.execute(a))};
gfc_7[gfc_].nu=function(a){var b=a.friends;b&&!b[gfc_xc]&&(this.d[gfc_k].friends=gfc_ue(b,gfc_pe));this.gn(a)};gfc_7[gfc_].Av=function(a){var b=gfc_e[gfc_H]();b.add(gfc_se("VIEWER"),"numWaitingMessages");b[gfc_n](a)};gfc_7[gfc_].pu=function(a){this.numWaitingMessages=a.get("numWaitingMessages")[gfc_l]().numberOfWaitingMessages};
gfc_7[gfc_].ov=function(a){this.log("requesting promo");var b=new gfc_a[gfc_Kc],b=b.getLang()+(b[gfc_rd]()?"_"+b[gfc_rd]():""),c=gfc_e[gfc_H]();c.add(gfc_he("GetPromo",{hl:b}),"promo");c[gfc_n](a)};gfc_7[gfc_].ju=function(a){this.log("processing promo");(a=a.get("promo")[gfc_l]())&&-1!=a.promoCode&&(this.promoCode=a.promoCode,this.promoHtml=a.promoHtml)};
gfc_7[gfc_].vo=function(){for(var a=function(){this.promoHtml=null;for(var a=gfc_bg("div","fc-promo-main",gfc_P("peg")),b=0;b<a[gfc_B];b++)gfc_4h(a[b],!1);this.Y();this.log("Dismissing promo "+this.promoCode);a=gfc_e[gfc_H]();a.add(gfc_he("DismissPromo",{promoCode:this.promoCode}));a[gfc_n](gfc_L(function(){this.log("The promo has been dismissed");this.promoCode=-1},this))},b=gfc_bg("a","fc-promo-dismiss-link",gfc_P("peg")),c=0;c<b[gfc_B];c++){var d=b[c],e="click";gfc_8i(d,e);gfc_Zi(d,e,gfc_L(a,this))}};
gfc_7[gfc_].gn=function(a){var b=a.isViewerAdmin;b&&!b[gfc_xc]?this.d[gfc_k].isViewerAdmin=b.list[gfc_B]:a.get&&a.get("isViewerAdmin")&&(a=a.get("isViewerAdmin"))&&!a[gfc_Jc]()&&(this.d[gfc_k].isViewerAdmin=a[gfc_l]()[gfc_Qb]())};gfc_7[gfc_].lo=function(a){var b=[];a.each(function(a){a={user:a[gfc_I](goog.opensocial.peoplesense.Invite[gfc_q].INVITER)[gfc_E](),action:"ACCEPT"};b[gfc_v](a)});this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.Ig,this),{friendRequestResponses:b})};
gfc_7[gfc_].Nw=function(){this.ga();this.render(["members","viewerFriends"],"faces")};gfc_7[gfc_].mo=function(a){a={user:a[gfc_E](),action:"ACCEPT"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.Ig,this),{friendRequestResponses:[a]})};gfc_7[gfc_].yx=function(){this.ga();this.B("friend-requests")};gfc_7[gfc_].bo=function(a){this.Lb()?(this.ga(),this.Ax(a)):gfc_ee(a[gfc_E]())};
gfc_7[gfc_].Ax=function(a){this.render(["profileData","profileFriends","activityData"],"profile",{person:a})};gfc_7[gfc_].uv=function(a,b){var c=gfc_e[gfc_H](),d=gfc_e[gfc_D][gfc_Wc],e={};e[d.FIRST]=b&&b[gfc_t]?b[gfc_t]:0;var f=this.d[gfc_k][gfc_o].person[gfc_E]();e[d.MAX]=this.Hn;c.add(gfc_ze(gfc_e[gfc_vc]({userId:f}),e),"profileSites");c[gfc_n](a)};gfc_7[gfc_].lu=function(a){this.d[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]()};
gfc_7[gfc_].lv=function(a,b){this.d[gfc_k].profile={};b=b||{};var c=b.person,d={},c=c[gfc_E](),e=gfc_e[gfc_H](),f=[gfc_e[gfc_x][gfc_q].ID,gfc_e[gfc_x][gfc_q][gfc_3a],gfc_e[gfc_x][gfc_q][gfc_Db],gfc_e[gfc_x][gfc_q].ABOUT_ME,gfc_e[gfc_x][gfc_q].URLS,"profileExtensions"],g=gfc_e[gfc_D][gfc_Wc];d[g[gfc_mc]]=f;d[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_9c];e.add(e.newFetchPersonRequest(c,d),"profile");e.add(e.newFetchPersonRequest("VIEWER",d),"viewer");e.add(gfc_xe("VIEWER","ADMINS"),
"isViewerAdmin");e.add(e.newFetchPersonRequest("OWNER",d),"owner");this.lb||e.add(gfc_re(),"siteSettings");e.add(gfc_xe(c,"ADMINS"),"isAdmin");e.add(gfc_xe(c,"BLOCKED"),"isBlocked");this.isMessagingEnabled&&e.add(gfc_se(c),"canMessage");e[gfc_n](a)};
gfc_7[gfc_].Nf=function(a,b){var c=b.person[gfc_E](),d=gfc_e[gfc_vc]({userId:c}),e=gfc_e[gfc_H]();(this.d[gfc_k].viewer&&c!=this.d[gfc_k].viewer[gfc_E]()||this.Lb())&&e.add(gfc_we(b.person[gfc_E](),"VIEWER"),"isProfileFriend");e.add(e[gfc_cd](d,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].hd=function(a,b){null!=a.get("activities")[gfc_l]()&&(this.d[gfc_k][gfc_o].activities=a.get("activities")[gfc_l]());var c=a.get("isProfileFriend");c&&b&&null!=this.d[gfc_k].viewer&&this.d[gfc_k].viewer[gfc_E]()!=b.person[gfc_E]()&&(this.d[gfc_k][gfc_o].isFriend=c[gfc_l]()[gfc_w])};
gfc_7[gfc_].gu=function(a,b){var c=a.get("profile")[gfc_l]();this.d[gfc_k][gfc_o].person=c;this.d[gfc_k][gfc_o].person.externalProfileUrl=null;var d=c[gfc_I](gfc_e[gfc_x][gfc_q].URLS),e=[];if(d)for(var f=0;f<d[gfc_B];f++){var g=d[f];"profile"!=g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&"externalProfile"!=g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&e[gfc_v](g);"externalProfile"==g[gfc_I](gfc_e.Url[gfc_q].TYPE)&&(this.d[gfc_k][gfc_o].person.externalProfileUrl=g[gfc_I](gfc_e.Url[gfc_q].ADDRESS))}this.d[gfc_k][gfc_o].links=
new gfc_fo(e,this.wf,0);this.d[gfc_k].owner=a.get("owner")[gfc_l]();this.d[gfc_k].viewer=a.get("viewer")[gfc_l]();(d=this.d[gfc_k].viewer)&&b.person[gfc_E]()!=this.d[gfc_k].viewer[gfc_E]()&&(this.d[gfc_k][gfc_o].isAdmin=a.get("isAdmin")[gfc_l](),this.d[gfc_k][gfc_o].isAdmin&&(this.d[gfc_k][gfc_o].isAdmin=this.d[gfc_k][gfc_o].isAdmin[gfc_Qb]()),this.d[gfc_k][gfc_o].isBlocked=a.get("isBlocked")[gfc_l](),this.d[gfc_k][gfc_o].isBlocked&&(this.d[gfc_k][gfc_o].isBlocked=this.d[gfc_k][gfc_o].isBlocked[gfc_Qb]()));
c=c[gfc_I]("profileExtensions");c=this.Pb.of(c,this.Pb.Zi);d=[];for(f in c){e=c[f];g={};g.title=e.title;var h=!1;if("SHORT_TEXT"==e[gfc_5c]||"LONG_TEXT"==e[gfc_5c])e[gfc_w]&&e[gfc_w][gfc_Ec]&&(g.body=[],g[gfc_C][gfc_v](e[gfc_w][gfc_Ec]),h=!0);else if(e[gfc_w]&&e[gfc_w].choice&&0<e[gfc_w].choice[gfc_B]){g.body=[];for(h=0;h<e[gfc_w].choice[gfc_B];++h)g[gfc_C][gfc_v](e[gfc_w].choice[h][gfc_qc]);h=!0}h&&d[gfc_v](g)}this.d[gfc_k][gfc_o].profileExtensions=d;this.lb||(this.lb=a.get("siteSettings")[gfc_l]());
this.isMessagingEnabled&&(f=(f=a.get("canMessage"))&&f[gfc_l]().canSendMessage,this.d[gfc_k][gfc_o].canSendMessage=f);this.gn(a)};gfc_7[gfc_].Kj=function(a){this.render(["blockUser"],"profile",{person:a})};gfc_7[gfc_].px=function(a){this.render(["unblockUser"],"profile",{person:a})};gfc_7[gfc_].map=function(a,b){var c=[],d=gfc_L(function(a,b,c){a[gfc_v](b(c))},this,c,b);a.each(d);return c};gfc_7[gfc_].zw=function(){this.ga();this.B("members-page")};
gfc_7[gfc_].Dw=function(){this.ga();this.render(["blocked-member-page"],"blocked-members-page",{start:0})};gfc_7[gfc_].Uw=function(){this.hj()};gfc_7[gfc_].ft=function(a){this.render(["member-page"],"members-page",{start:this.ma+a.getOffset()})};gfc_7[gfc_].Mt=function(a){this.render(["member-page"],"members-page",{start:a.getOffset()-this.ma})};gfc_7[gfc_].at=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:this.ma+a.getOffset()})};
gfc_7[gfc_].Kt=function(a){this.render(["blocked-member-page"],"blocked-members-page",{start:a.getOffset()-this.ma})};gfc_7[gfc_].Cw=function(){this.ga();this.B("viewer-friends-page")};gfc_7[gfc_].mt=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:this.ma+a.getOffset()})};gfc_7[gfc_].St=function(a){this.render(["viewerFriends"],"viewer-friends-page",{start:a.getOffset()-this.ma})};gfc_7[gfc_].Aw=function(){this.ga();this.B("profile-friends-page")};
gfc_7[gfc_].kt=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:this.ma+a.getOffset(),person:this.d[gfc_k][gfc_o].person})};gfc_7[gfc_].Qt=function(a){this.render(["profile-friends-page"],"profile-friends-page",{start:a.getOffset()-this.ma,person:this.d[gfc_k][gfc_o].person})};gfc_7[gfc_].yw=function(){this.ga();this.B("links")};gfc_7[gfc_].et=function(a){var b=this.wf+a.getOffset();this.d[gfc_k][gfc_o].links=new gfc_fo(a.all(),this.wf,b);this.B("links")};
gfc_7[gfc_].Lt=function(a){var b=a.getOffset()-this.wf;this.d[gfc_k][gfc_o].links=new gfc_fo(a.all(),this.wf,b);this.B("links")};gfc_7[gfc_].Bw=function(){this.ga();this.B("sites")};gfc_7[gfc_].lt=function(a){this.render(["sitesData"],"sites",{start:this.Hn+a.getOffset()})};gfc_7[gfc_].Rt=function(a){this.render(["sitesData"],"sites",{start:a.getOffset()-this.Hn})};gfc_7[gfc_].ww=function(){this.ga();this.B("activities")};
gfc_7[gfc_].$s=function(a){this.render(["activityData"],"activities",{start:this.Ba+a.getOffset()})};gfc_7[gfc_].Jt=function(a){this.render(["activityData"],"activities",{start:a.getOffset()-this.Ba})};gfc_7[gfc_].df=function(a){this.render(["deleteActivity"],this.d[gfc_hd],{activity:a})};gfc_7[gfc_].$u=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_ye(b.person[gfc_E](),["BLOCKED"],[]),"block");this.ad();c[gfc_n](a)};
gfc_7[gfc_].Yt=function(a){if(a=!a.get("block")[gfc_Jc]())this.d[gfc_k][gfc_o].isBlocked=!0};gfc_7[gfc_].xv=function(a,b){var c=gfc_e[gfc_H]();c.add(gfc_ye(b.person[gfc_E](),[],["BLOCKED"]),"unblock");this.ad();c[gfc_n](a)};gfc_7[gfc_].mu=function(a){if(a=!a.get("unblock")[gfc_Jc]())this.d[gfc_k][gfc_o].isBlocked=!1};
gfc_7[gfc_].Of=function(a,b){var c=b.activity,d=c[gfc_I](gfc_e[gfc_cc][gfc_q].ID),c=gfc_e[gfc_vc]({userId:c[gfc_I](gfc_e[gfc_cc][gfc_q][gfc_2b])}),e=gfc_e[gfc_H]();e.add(gfc_ie(d),"delete");e.add(e[gfc_cd](c,{}),"activities");e[gfc_n](a)};
gfc_7[gfc_].hc=function(a){var b=gfc_En,c=function(a){return a=a[gfc_j](/<a/g,"<a target='_top'")},d=null,e=this.d[gfc_k].viewer;null!=e&&a[gfc_I](gfc_e[gfc_cc][gfc_q][gfc_2b])==this.d[gfc_k].viewer[gfc_E]()&&(d=gfc_L(this.df,this,a));(e=a[gfc_I](gfc_e[gfc_cc][gfc_q].STREAM_FAVICON_URL,{escapeType:"none"}))||(e=gfc_b.friendconnect_imageUrl+"/favicons.gif");return{icon:e,time:b(gfc_ga(a[gfc_I](gfc_e[gfc_cc][gfc_q].POSTED_TIME))),link:a[gfc_I](gfc_e[gfc_cc][gfc_q].STREAM_URL,{escapeType:"none"}),siteTitle:a[gfc_I](gfc_e[gfc_cc][gfc_q].STREAM_TITLE,
{escapeType:"none"}),innerHTML:c(a[gfc_I](gfc_e[gfc_cc][gfc_q].TITLE,{escapeType:"none"})),body:c(a[gfc_I](gfc_e[gfc_cc][gfc_q].BODY,{escapeType:"none"})),deleteHandler:d}};gfc_7[gfc_].lx=function(a){var b=gfc_a[gfc_ic].unescapeString,c=gfc_do;return{icon:c(a[gfc_I](gfc_e[gfc_x][gfc_q][gfc_Tc])),link:a[gfc_I](gfc_e[gfc_x][gfc_q][gfc_Tc]),title:b(a[gfc_3b]())}};
gfc_7[gfc_].kx=function(a){var b=gfc_a[gfc_ic].unescapeString,c=gfc_do,d=a[gfc_I](gfc_e.Url[gfc_q].ADDRESS);return{icon:c(d),link:d,title:b(a[gfc_I](gfc_e.Url[gfc_q].LINK_TEXT))||d}};gfc_7[gfc_].nv=function(a,b){var c=gfc_e[gfc_H](),d=b.person[gfc_E](),e=gfc_e[gfc_D][gfc_Wc],f=this.im(d),g={};g[gfc_e[gfc_D].DataRequestFields.ESCAPE_TYPE]=gfc_e.EscapeType[gfc_9c];c.add(c[gfc_ac](f,g),"friends");f={};f[e.FIRST]=this.Ny;f[e.MAX]=this.My;c.add(gfc_ze(gfc_e[gfc_vc]({userId:d}),f),"profileSites");c[gfc_n](a)};
gfc_7[gfc_].Ur=function(a){a={user:a[gfc_E](),action:"DENY"};this.render(["sendFriendRequestResponse","members","viewerFriends"],gfc_L(this.Ig,this),{friendRequestResponses:[a]})};gfc_7[gfc_].Ig=function(a){return a&&a["next-view"]?a["next-view"]:["friend-requests"]};gfc_7[gfc_].tv=function(a,b){var c=b[gfc_o],d=gfc_e[gfc_H]();d.add(gfc_je(c[gfc_E](),b.message),"friendRequest");this.ad();d[gfc_n](a)};gfc_7[gfc_].ku=function(a){a.get("friendRequest")[gfc_Jc]()||(this.d[gfc_k][gfc_o].isInvited=!0)};
gfc_7[gfc_].dv=function(a,b){var c=gfc_bo.newBatch(),d=b.friendRequestResponses;c.add("updateFriendRequest",gfc_bo.extensions.get({command:"ProcessFriendRequests",params:'{"requests":'+gfc_a[gfc_fc].stringify(d)+"}"}));c.add("friendRequests",gfc_bo.extensions.get({command:"GetFriendRequests",params:'{"idSpec" : "VIEWER"}'}));this.ad();c.execute(a)};gfc_7[gfc_].Xq=function(){this.ga();this.B("invite-friend")};gfc_7[gfc_].Uv=function(a){this.isMessagingEnabled&&(a=a[gfc_I](gfc_e[gfc_x][gfc_q].ID),this.Vv(a))};
gfc_7[gfc_].Vv=function(a){this.isMessagingEnabled&&(a="/friendconnect/messaging/compose?recipientId="+a,gfc_nn(a,"570","395"))};gfc_1[gfc_].no=function(){gfc_nn("/friendconnect/messaging/accept","570","375");return!1};gfc_7[gfc_].Wq=function(){this.ga();this.B("block-member")};gfc_7[gfc_].Yq=function(){this.bo(this.d[gfc_k].viewer)};gfc_7[gfc_].Tv=function(a){this.Cf();a={profile:a};var b=gfc_P("inviteMessage");b&&(a.message=gfc_th(b));this.render(["sendFriendRequest"],"profile",a)};
gfc_7[gfc_].Io=function(a){this.Cf();this.Kj(a)};gfc_7[gfc_].Am=function(a,b,c){c=c||!1;this.d[gfc_k].friendRequests=gfc_ue(a.friendRequests,gfc_le);0<this.d[gfc_k].friendRequests[gfc_Qb]()?b["next-view"]="friend-requests":b["next-view"]="faces";c||gfc_9m("friend")};gfc_7[gfc_].iu=function(a){this.d[gfc_k][gfc_o].sites=a.get("profileSites")[gfc_l]();this.d[gfc_k][gfc_o].friends=a.get("friends")[gfc_l]()};gfc_7[gfc_].Jq=function(){return this.Lw};
gfc_7[gfc_].Y=function(){this.jy.rebuild();this.vo();gfc_a[gfc_4c].adjustHeight()};gfc_7[gfc_].zt=function(a){return a=gfc_Q("span",{"class":"fc-cap-link-big"},gfc_Q("a",{"class":"fc-cap-link-big"},this.e.MSG_OPTIONS),a.Og())};
gfc_7[gfc_].yt=function(){var a=[];a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-settings"},this.e.MSG_SITE_SETTINGS);this.isSocialShareEnabled&&(a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-share"},this.e.MSG_MEMBERS_SHARE));this.d[gfc_k].isViewerAdmin&&!this.Lb()&&(a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-manage"},this.e.MSG_MANAGE));a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-signout"},this.lb.signOutPrompt||this.e.MSG_SIGN_OUT);a[a[gfc_B]]=
gfc_Q("div",{"class":"goog-menuseparator fc-menuseparator-line"});a[a[gfc_B]]=gfc_Q("div",{"class":"goog-menuitem menuaction-aboutfc"},gfc_Q("span",{"class":"fc-small-menu-link"},this.e.MSG_ABOUT_FC));return a};
gfc_7[gfc_].At=function(a){a[gfc__b]();a=a[gfc_F].g()[gfc_6c];a[gfc_hb]("menuaction-settings")?this.Db():a[gfc_hb]("menuaction-share")?this.share():a[gfc_hb]("menuaction-signout")?this.signout():a[gfc_hb]("menuaction-manage")?this.br():a[gfc_hb]("menuaction-aboutfc")&&(a=gfc_b[gfc_Bc](gfc_fn()+"/friendconnect/home/overview"),a[gfc_nb]())};gfc_7[gfc_].br=function(){var a={},b=gfc_a[gfc_r][gfc_9a]()[gfc_sc];gfc_9m("lightbox");gfc_a[gfc_r].requestNavigateTo(b,a);return!1};
var gfc_eo=function(a){for(var b={},c=0;c<a[gfc_B];++c)b[a[c]]=a[c];return b}("HEIGHT BORDER_COLOR CONTENT_BG_COLOR CONTENT_HEADLINE_COLOR CONTENT_LINK_COLOR CONTENT_SECONDARY_TEXT_COLOR CONTENT_SECONDARY_LINK_COLOR CONTENT_TEXT_COLOR ENDCAP_BG_COLOR ENDCAP_LINK_COLOR ENDCAP_TEXT_COLOR FACE_SIZE NUMBER_ROWS".split(" "));
gfc_7[gfc_].s=function(){var a=gfc_eo,b=[],c=0;this.f(a.HEIGHT);this.bi()&&(b[c++]=this.j(".fc-thumbnail img {height:%spx;width:%spx}",this.f(a.FACE_SIZE)));b[c++]=this.j(".fc-scroll-botnav, .fc-scroll, .fc-noscroll-botnav {height: %spx;}\n",this.bn);b[c++]=this.j(".fc-members,.fc-members-canvas {border-color: %s;}\n.fc-userpage-itemlist,.fc-userpage-itemlist-canvas,.fc-botcap-short { border-top-color: %s; }\n.fc-topcap,.fc-topverb,.fc-friendreq,.fc-friendreqs,.fc-timeframe { border-bottom-color: %s; }\n",
this.f(a.BORDER_COLOR));this.mf()&&(this.ol("profile")?b[c++]=".fc-topcap {height: "+this.slimTopCapHeight+"px;}\n":this.fi()?b[c++]=".fc-topcap {height: 0px;}\n":b[c++]=".fc-topcap {height: "+this.tinyTopCapHeight+"px;}\n");this.Lb()?b[c++]=".fc-userpic-caption {margin-left: 59px;}\n":b[c++]=".fc-userpic-caption {margin-left: 40px;}\n";this.fi()?b[c++]=".fc-topcap-color {background-color: white;}\n":b[c++]=this.j(".fc-topcap-color {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));this.El()?b[c++]=
".fc-botcap-short {background-color: white;}\n":b[c++]=this.j(".fc-botcap-short {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-botverb, .fc-topverb, .fc-members-header {background-color: %s;}\n",this.f(a.ENDCAP_BG_COLOR));b[c++]=this.j(".fc-topcap, .fc-botverb, .fc-topverb, .fc-botcap-short, .fc-header-sectitle, .fc-members-header {color: %s;}\n",this.f(a.ENDCAP_TEXT_COLOR));
b[c++]=this.j(".fc-botverb,.fc-topcap .fc-menutriangle-down, .fc-topcap .fc-menutriangle-up,.fc-topcap a, .fc-topcap a:active, .fc-topcap a:visited,.fc-topcap-link a, .fc-topcap-link a:active, .fc-topcap-link a:visited,.fc-cap-link-big a, .fc-cap-link-big a:active,.fc-left-verb a, .fc-left-verb a:active, .fc-left-verb a:visited,.fc-right-verb a, .fc-right-verb a:active, .fc-right-verb a:visited,.fc-subtle-botcap a, .fc-subtle-botcap a:active, .fc-subtle-botcap a:visited.fc-left-verb-canvas a, .fc-left-verb-canvas a:active, .fc-left-verb-canvas a:visited,.fc-right-verb-canvas a, .fc-right-verb-canvas a:active, .fc-right-verb-canvas a:visited {color: %s;}\n",
this.f(a.ENDCAP_LINK_COLOR));b[c++]=this.j(".fc-content-bg, .fc-subtle-botcap {background-color:%s;}\n",this.f(a.CONTENT_BG_COLOR));b[c++]=this.j(".fc-content a, .fc-content a:active, .fc-content a:visited,\n.fc-item-body a, .fc-item-body a:active, .fc-item-body a:visited,\n.fc-see-all a, .fc-see-all a:active, .fc-see-all a:visited,\n.fc-content-link a, .fc-content-link a:active, .fc-content-link a:visited,\n.fc-content-canvas a, .fc-content-canvas a:active, .fc-content-canvas a:visited {color: %s;}\n",
this.f(a.CONTENT_LINK_COLOR));b[c++]=this.j(".fc-members,.fc-members-canvas {color:%s;}\n",this.f(a.CONTENT_TEXT_COLOR));b[c++]=this.j(".fc-helpful,.fc-on-other-site,.fc-no-elements, .ot-activity-metadata {color:%s;}\n",this.f(a.CONTENT_SECONDARY_TEXT_COLOR));b[c++]=this.j(".fc-faded-link a, .fc-faded-link a:active, .fc-faded-link a:visited, .fc-faded-link-small a, .fc-faded-link-small a:active, .fc-faded-link-small a:visited {color: %s;}\n",this.f(a.CONTENT_SECONDARY_LINK_COLOR));b[c++]=this.j(".fc-sectitle {color: %s;}\n",
this.f(a.CONTENT_HEADLINE_COLOR));return gfc_7.i.s[gfc_G](this)+b[gfc_J]("\n")};gfc_M("goog.peoplesense.gadget.Members",gfc_7);gfc_M("goog.peoplesense.gadget.Members.start",gfc_7[gfc_t]);var gfc_fo=function(a,b,c){gfc_e.Collection[gfc_G](this,a[gfc_Gc](c,c+b),c,a[gfc_B]);this.Lx=a;this.ea=b};gfc_fo.inherits(gfc_e.Collection);gfc_fo[gfc_].all=function(){return this.Lx};gfc_fo[gfc_].rb=function(){return this.ea};gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.all",gfc_fo[gfc_].all);
gfc_M("goog.peoplesense.gadget.Members.PagedCollection.prototype.getPageSize",gfc_fo[gfc_].rb);
